<!DOCTYPE html>
<html>
    <head>
        <title>Promise</title>
    </head>
    <body>
        <script type="text/javascript">

            // => Synchronous Javascript 
                // Note :: Javascript can run ONE statement at a time 
            console.log('result one'); 
            console.log('result two');
            console.log('result three');

            // => Asynchronous Javascript 
            
            console.log('data one'); 
            console.log('data two');
            console.log('data three');

            setTimeout(()=>{
                console.log("callback function is start working now")
            },5000);

            console.log('data four'); 
            console.log('data five');
            console.log('data six');

            const promise = new Promise((resolve,reject)=>{

                setTimeout(()=>{
                    resolve();
                },3000);

                setTimeout(()=>{
                    reject();
                },3000);

            });

            promise.then(()=>console.log('Finally Finished'))
                    .then(()=>console.log('I was also run'))
                    .catch(()=>console.log('I catched you!'));
            
            // => without async/await (using Promise)

            fetch('https://jsonplaceholder.typicode.com/posts/1').then((response)=>{
                // console.log('resolved',response);

                if(!response.ok){
                    throw new Error("Network response was not oki sir");
                }

                return response.json();
            }).then(data=>{
                console.log(data);
                console.log(data.id);
                console.log(data.title);
                console.log(data.body);
            }).catch((err)=>{
                console.log('rejected',err);
            });

            // => async & await fetch()

            const getpost = async ()=>{
                const response = await fetch('https://jsonplaceholder.typicode.com/posts/1'); 
                const data = await response.json(); 

                return data;
            }

            getpost().then(data=>{
                // console.log(data);

                console.log(data.id);
                console.log(data.title);
                console.log(data.body);
            })

            // => Error Handling for without async/await (using Promise)

            fetch('https://jsonplaceholder.typicode.com/posts/1').then((response)=>{
                // console.log('resolved',response);

                if(!response.ok){
                    throw new Error("Network response was not oki sir");
                }

                return response.json();
            }).then(data=>{
                // console.log(data);
                console.log(data.id);
                console.log(data.title);
                console.log(data.body);
            }).catch((err)=>{
                console.log('rejected',err);
            });

            // => Error Handling for async & await fetch()

            async function fetchdata(){
                try{
                    const response = await fetch('https://jsonplaceholder.typicode.com/posts/1'); 
                    // console.log(response); 

                    if(!response.ok){
                        throw new Error("Network response was not oki sir")
                    }
                    const data = await response.json(); 
                    return data;
                }catch(error){
                    console.log("There has been a problem with data = ", error);
                }
            }

            fetchdata();


        </script>
    </body>
</html>

<!-- 
=>Synchronous (Single Threaded) 
statement 1
statement 2 - - - - - - database
statement 3
statement 4 - - - - - - database
statement 5
 -->


<!-- 
 =>Asynchronous (Single Threaded) 
statement 1
statement 2 - - - - - - database
statement 3                -
statement 4                -
statement 5                -
callback    - - - - - -
 -->

<!-- 

 => Differences  

 promise = can become complex and less readable .then() .catch()

 async/await = looks more like Synchronous code , making it easier to read and maintain 

 promise = Error handling is doing using .catch 
 async/await = Error handling is doing using try... catch blocks / mor naturally with Asynchronous operation (such as loops and conditionals)


  -->

  <!-- 28OV -->